behaviors:
  PoliceAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 150
      learning_rate: 0.0003
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000

  ThiefAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 150
      learning_rate: 0.0003
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000